apiVersion: v1
kind: PersistentVolume

metadata:
  name: mywebpvc
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 500Mi 
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
